### ISSUE TITLE
Error: Cannot delete /admin/install.php, /admin/setup.php or /admin/update.php. Please do this manually.

### ISSUE THREAD

**Issue by lance1572** [GetSimpleCMS-CE/GetSimpleCMS-CE#10]
Hi!

I get this persistent error after I manually delete the install, setup and update files. I poked around and found this block of code in inc/common.php:320. Doing some logging it seems the `$filedeletionstatus` gets lost after the option check. 

Are the checks for the option, license and readme important here? I'm not totally sure what the` GSDEBUGINSTALL` is doing for this conditional. I suppose its setting the`  GSDEBUGINSTALL` to true in the arg and the condition is checking if its true. Then it checks for those files.

 I did notice that the license is not in the .zip file so that is most likely where it poops. 😆  I just removed the three conditionals (option, license and readme ) and the error went away.

`

        if(!getDef('GSDEBUGINSTALL',true)){	
		# if you've made it this far, the site is already installed so remove the installation files
		$filedeletionstatus=true;

		if (file_exists(GSADMINPATH.'install.php'))	{
			$filedeletionstatus = unlink(GSADMINPATH.'install.php');
		}
	
		if (file_exists(GSADMINPATH.'setup.php'))	{
			$filedeletionstatus = unlink(GSADMINPATH.'setup.php');
		}
		if (file_exists(GSADMINPATH.'update.php'))	{
			$filedeletionstatus = unlink(GSADMINPATH.'update.php');
		}

		if (file_exists(GSADMINPATH.'option.txt'))	{
			$filedeletionstatus = unlink(GSADMINPATH.'option.txt');
		}
		if (file_exists('../README.md'))	{
			$filedeletionstatus = unlink('../README.md');
		}
		if (file_exists('../LICENSE'))	{
			$filedeletionstatus = unlink('../LICENSE');
		}
		if (!$filedeletionstatus) {
			$error = sprintf(i18n_r('ERR_CANNOT_DELETE'), '<code>/'.$GSADMIN.'/install.php</code>, <code>/'.$GSADMIN.'/setup.php</code> or <code>/'.$GSADMIN.'/update.php</code>');
		}
	}	

`

thanks!

lance1572

**Comment by risingisland** [comment]
Hey, 
Strange that this would through any error. 
This is just a cleanup after install/upgrade. 
Basically it is checking to see if those files exist and if so, remove them.
If it doesnt exist, move on, nothing to see here.

Could you post what the error is?
Also, is this on localhost or server, and what version of php?

**Comment by risingisland** [comment]
Thank. I will be updating this in the next release.

You can try this to see if it resolves this issue or not:

After the line (near 23):
`define('GSAUTOSAVEPATH', GSROOTPATH. 'data/pages/autosave/');`
add:
`define('GSHOMEPATH', GSROOTPATH. '/');`

Update lines (near 335):
```
	if (file_exists('../README.md'))	{
		$filedeletionstatus = unlink('../README.md');
	}
	if (file_exists('../LICENSE'))	{
		$filedeletionstatus = unlink('../LICENSE');
	}
```
to:
```
		if (file_exists(GSHOMEPATH.'README.md'))	{
			$filedeletionstatus = unlink(GSHOMEPATH.'README.md');
		}
		if (file_exists(GSHOMEPATH.'LICENSE'))	{
			$filedeletionstatus = unlink(GSHOMEPATH.'LICENSE');
		}
```

**Comment by lance1572** [comment]
Unfortunately, that didn't work for me. I manually deleted the options, readme and license and it worked.

I was initially focused only on the 3 files (install, setup and update) as thats what the dialog on the front-end indicated. 

Thank you for responding. 

Lance
