### ISSUE TITLE
/data/.htaccess blocks my scripts

### ISSUE THREAD

**Issue by johnaweiss** [GetSimpleCMS-CE/GetSimpleCMS-CE#5]
i put custom .js scripts in /data/scripts. Apparently their execution is blocked by /data/.htaccess
How to fix? Here's my /data/.htaccess

```
#
# GetSimple CMS htaccess DENY file
#

# prevent breaking plugin htaccess, prefer compat,  since require is not overridable by order

# apache < 2.3
<IfModule !mod_authz_core.c>
	Deny from all
</IfModule>

# apache > 2.3 with mod_access_compat
<IfModule mod_access_compat.c>
	Deny from all
</IfModule>

# apache > 2.3 without mod_access_compat
<IfModule mod_authz_core.c>

	<IfModule !mod_access_compat.c>
		Require all denied
	</IfModule>

</IfModule>	
```

**Comment by risingisland** [comment]
The contents of `/data/` is readable by the cms only, and not publicly viewable, as this contains login data etc.
I am assuming your custom .js is for a theme and this should be placed in the themes folder. If it is for a custom plugin, then it should be placed in the plugins folder with .htaccess permissions adjusted.
