### ISSUE TITLE
Child Themes?

### ISSUE THREAD

**Issue by johnaweiss** [GetSimpleCMS-CE/GetSimpleCMS-CE#6]
Does gsce support child-themes, like wordpress, to receive theme updates without breaking my customizations?

**Comment by risingisland** [comment]
I dont use Wordpress, so I am not sure what you mean by child-themes.
You can only use one theme at a time, but you are able to add different types of pages with their own css/js in each theme.
For example, if you are using one of the bundled themes that GS-CE comes with, the default for a page is `template.php`, but you can copy and rename this, for example, `blog.php`, and then change the header/footer to what ever your sub-theme is needing.
Then in your Blog page, just choose "blog.php" from dropdown.
If I am not explaining this clearly, or not understanding your question, please rephrase.

**Comment by risingisland** [comment]
Yes, that would work fine.

**Comment by johnaweiss** [comment]
to share between themes, is it fine to create a new dir at this dir?
/theme/common/scripts

**Comment by risingisland** [comment]
All files withing /theme/ are publicly accessible, so that should work fine.
You could have something like:
  /theme/FirstTheme/
  /theme/SecondTheme/
  /theme/common/
where common holds css/js that are used in the first two.
But, you would need to provide the full path to this.

**Comment by johnaweiss** [comment]
Relative paths seems to work fine.

**Comment by risingisland** [comment]
Perfect. Glad to hear it.
