### ISSUE TITLE
Responsive File Manager is blank

### ISSUE THREAD

**Issue by johnaweiss** [GetSimpleCMS-CE/GetSimpleCMS-CE#8]
Responsive File Manager is blank

![image](https://github.com/GetSimpleCMS-CE/GetSimpleCMS-CE/assets/53209681/959ce769-5050-4cbb-b2a6-bc4745ea5d76)

**Comment by risingisland** [comment]
That plugin quite working ages ago do to its script dependency no longer being supported.
I had started to work on updating this, but didnt have much luck. You can take a look here:
https://github.com/GetSimpleCMS-CE-plugins/plugin-Responsive_FileManager_CE

**Comment by risingisland** [comment]
@johnaweiss PS, you can view known php8.x compatible plugins here:
https://getsimple-ce.ovh/ce-plugins/
